### PR TITLE
Fixes/ppbnumber-issues.

### PR DESCRIPTION
**Pull request by ananjaykumar2**
this **PR**  includes:
- ppbNumber reated changes 
- code coverage 90%
- separate postman collection for adex

### CODE REVIEW

**Comment by pranavv0** [comment]
retest this please

**Comment by pranavv0** [comment]
retest this please

**Comment by pranavv0** [comment]
retest this please

**Comment by pranavv0** [comment]
retest this please

**Comment by pranavv0** [comment]
lgtm. Pipeline is passing.

**Review by pranavv0 — APPROVED** [review]
LGTM

**Review by ankitmashu — APPROVED** [review]
LGTM

**Review by pranavrd — APPROVED** [review]

**Pull request merged**
